App\Entity\Membre:
  properties:
    nom:
      - NOTNULL: ~
      - NOTBLANK: ~
      - Type:
          type: string
          message: Le champ {{ value }} n'est pas un type {{ type }} valide
      - Length:
          min: 3
          max: 45
          minMessage: Champ 'Nom' doit obligatoirement avoir au moins {{ limit }} caractères
          maxMessage: Champ 'Nom' ne doit pas avoir plus de {{ limit }} caractères

    prenom:
      - NOTNULL: ~
      - NOTBLANK: ~
      - Type:
          type: string
          message: Le champ {{ value }} n'est pas un type {{ type }} valide
      - Length:
          min: 1
          max: 45
          minMessage: Champ 'Prenom' doit obligatoirement avoir au moins {{ limit }} caractères
          maxMessage: Champ 'Prenom' ne doit pas avoir plus de {{ limit }} caractères

    civilite:
      - NOTNULL: ~
      - NOTBLANK: ~
      - Type:
          type: string
          message: Le champ {{ value }} n'est pas un type {{ type }} valide
      - Length:
          min: 1
          max: 1
          minMessage: Champ 'Civilité' doit obligatoirement avoir au moins {{ limit }} caractères
          maxMessage: Champ 'Civilité' ne doit pas avoir plus de {{ limit }} caractères
